version: '3.8'

# Service definition
services:
  swaggerUI:
    image: swaggerapi/swagger-ui:latest
    container_name: swaggerUI
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.252
    ports:
      - "1071:8080"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24