version: '3.8'

# Service definition
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    volumes:
      - metabaseVolume:/metabase-data
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.222
    ports:
      - "6002:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition
volumes:
  metabaseVolume:
    name: metabaseVolume