version: '3.8'

# Service definition
services:
  memcached:
    image: memcached:1.6.9-alphine # change with your preferred image tag
    container_name: memcached
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.26
    ports:
      - "11211:11211"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24