version: '3.8'

# Service definition
services:
  neo4J:
    image: neo4j:latest # change to your preferred image tag
    container_name: neo4J
    volumes:
      - neo4JVolume:/data
      - neo4JVolume:/logs
      - neo4JVolume:/var/lib/neo4j/import
      - neo4JVolume:/plugins
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.15
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/johndoe123 # change to your preferred Neo4J auth username and password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_HEAP_MEMORY=2G
      - NEO4J_CACHE_MEMORY=1G
      - NEO4J_dbms.connector.bolt.address=0.0.0.0:7687
      - NEO4J_dbms.connector.bolt.tls_level=OPTIONAL
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition
volumes:
  neo4JVolume:
    name: neo4JVolume