version: '3.8'

# Service definition
services:
  mongoDB:
    image: mongo:latest # change to your preferred image tag
    container_name: mongoDB
    volumes:
      - mongoDBVolume:/data/db
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.11
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "johndoe" # change to your preferred root username
      MONGO_INITDB_ROOT_PASSWORD: "johndoe123" # change to your preferred root password
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition
volumes:
  mongoDBVolume:
    name: mongoDBVolume