version: '3.8'

# Service definition
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkinsVolume:/var/jenkins_home
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.126
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Dhudson.footerURL=https://badricreative.tech"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition
volumes:
  jenkinsVolume:
    name: jenkinsVolume